#!/bin/sh
set -eu
ARCH=$(uname -m)

echo "Installing package dependencies..."
echo "---------------------------------------------------------------"
pacman -Syu --noconfirm \
    cmake          \
    libusb         \
    qt6-base       \
    qt6-tools      \
    vulkan-headers \
    patchelf

echo "Installing debloated packages..."
echo "---------------------------------------------------------------"
get-debloated-pkgs --add-common --prefer-nano

echo "Configuring OpenXgpro..."
echo "---------------------------------------------------------------"
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DOXGPRO_BUILD_TESTS=OFF

# Pull product metadata generated by CMake (OXGPRO_PRODUCT_NAME,
# OXGPRO_EXECUTABLE_NAME, OXGPRO_DESKTOP_ID). Single source of truth lives in
# the OXGPRO_* cache variables in the root CMakeLists.txt; override with -D.
. ./build/packaging/appimage_env.sh

cmake --build build --target "${OXGPRO_EXECUTABLE_NAME}"

# Copy the version file to dist directory
mkdir -p ./dist
cp build/VERSION.txt ./dist/VERSION.txt

mkdir -p ./AppDir/bin
cp -v ./packaging/"${OXGPRO_DESKTOP_ID}.png" ./AppDir/
cp -v ./build/packaging/"${OXGPRO_DESKTOP_ID}.desktop" ./AppDir/

# AppStream metainfo. The path is fixed by convention, not by our layout: the
# AppImageHub catalog scanner and desktop-integration tools like Gear Lever
# look in usr/share/metainfo/ specifically, even though sharun otherwise
# builds a flat AppDir with no usr/ prefix.
mkdir -p ./AppDir/usr/share/metainfo
cp -v ./build/packaging/"${OXGPRO_BUNDLE_IDENTIFIER}.metainfo.xml" \
      ./AppDir/usr/share/metainfo/

read -r VERSION < ./dist/VERSION.txt
export ARCH VERSION
export OUTPATH=./dist
# quick-sharun reads APPNAME to construct the AppImage filename.
export APPNAME="${OXGPRO_EXECUTABLE_NAME}"
export DEPLOY_OPENGL=1

quick-sharun "./build/${OXGPRO_EXECUTABLE_NAME}"
quick-sharun --make-appimage
